# 服务器的端口和contextPath的配置
server:
 port: 1111
 contextPath: /springboot
 
spring:
 datasource:  # 数据库的配置
  url: jdbc:mysql://localhost:3306/mytest
  username: root
  password: 111111
  driver-class-name: com.mysql.jdbc.Driver
 devtools: # 热部署机制 需要依赖一个jar
  restart:
   enabled: true

# MyBatis 的配置
mybatis:
 typeAliasesPackage: com.zhangheng.entity
 mapperLocations: classpath:mapper/*.xml

# 日志管理
logging:
 level:
  com:
   zhangheng:
    dao: debug
 file:
  logs/spring-boot-logging.log

# 权限验证
security:
 user:
  name: iflytek2018
  password: iflytek2018